### ISSUE TITLE
load_filings should actually load filings into the DB

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/nyt-campfin#2]
Maybe steal some of the code from the dump_csv methods Jacob was working on?

**Comment by jeremyjbowers** [comment]
Errors now because Filing model and filing object from nyt-pyfec have wildly incompatible fields.

**Comment by jeremyjbowers** [comment]
This line is currently failing (if you try) for many reasons, but mostly because the filing object has bad keys. https://github.com/newsdev/nyt-campfin/blob/feature-2/campfin/management/commands/load_filings.py#L101

**Comment by jeremyjbowers** [comment]
This is the area that would be able to properly format the headers and pass the correct attributes to the Filing Django model: https://github.com/newsdev/nyt-campfin/blob/feature-2/campfin/utils.py#L165

**Comment by jeremyjbowers** [comment]
The actual contributions (SkedA, SkedB, SkedE, SkedOther) are inserting properly. Just hung up on filings.

**Comment by rshorey** [comment]
closed by #16
