### ISSUE TITLE
Management command to load a filing by ID

### ISSUE THREAD

**Issue by cjdd3b** [newsdev/nyt-campfin#28]
Because sometimes you have to load/reload a filing. Derek's app has logic we can follow for this.

**Comment by rshorey** [comment]
so, this is not trivial, there's no easy way to look one of these up by filing_id as far as I can tell. would it be OK to also require the committee ID (in which case I can construct a URL?) Or @cjdd3b do you know of any way to find these by filing_id?

**Comment by cjdd3b** [comment]
Including committee ID is fine!

**Comment by rshorey** [comment]
ok, cool, then it's easy!

**Comment by rshorey** [comment]
closed by #43
