### ISSUE TITLE
Parse form F24s

### ISSUE THREAD

**Issue by cjdd3b** [newsdev/nyt-campfin#30]
These are 24-hour independent expenditure reports, which are important for tracking large ad buys and other big spends. The parser currently skips them. We can steal the schema for these from the independent_expenditures table in Derek's app.

**Comment by rshorey** [comment]
@cjdd3b, @jeremyjbowers, do you know anything about the difference between 24-hour and 48-hour ie reports? it looks like F24's are sometimes called one and sometimes the other. Doing some research, but figured worth asking in case you know. (no need to respond during your vacation - I probably won't get far on this till next week)

**Comment by rshorey** [comment]
note to self: pulling in F24's locally, but it's throwing warnings about totals that do not exist for this kind of form, need to figure out if we expect something, where to find it, and if not, stop throwing this warning.

**Comment by cjdd3b** [comment]
The law is here: http://www.fec.gov/info/charts_ie_dates_special.shtml

The idea is that reporting deadlines tighten as elections get closer. The same is true for contribs/expenditures.

**Comment by rshorey** [comment]
ok, thanks Chase, this makes sense. I should be pulling these forms shortly, but am still working on what to do with totals.

**Comment by rshorey** [comment]
partially resolved by #44 and work in nyt-pyfec. schedule E's now being loaded from F24s. The current app is not pulling totals from F24s, but is waiting until quarterly files come in to do totals.

It remains to check whether schedule E's get double-imported if they exist in both a F24 and a F3, I want to do that before closing that issue

**Comment by rshorey** [comment]
F24s and F3s duplicate schedule E lines, but have different transaction id's for the same transaction. Current proposal is to deactivate all schedule E's from F24's in the filing period whenever a F3 comes in.

**Comment by cjdd3b** [comment]
Do they duplicate one-for-one? If the SkedE's in the F3 are just a rehash of the F24s, we may just be able to take the F24s as the canonical source of independent expenditures. I think (?) that's what Derek did, but I can check.

**Comment by rshorey** [comment]
I think they are 1-1, but it's hard to know for sure because not many committees had independent expenditures prior to the midterm (note to self: Rick Perry's Opportunity and Freedom does).

I like this idea, and will do some more research to make sure.

**Comment by rshorey** [comment]
I read some FEC rules and talked to some folks who have dealt with this, and it sounds like the consensus is that the only way to have 1) realtime information about PACs AND 2) totals that match the quarterly reports is to pull the F24s and then delete the corresponding schedule E's when the quarterly comes in.

Unless we don't need one of those things, I'll start down that path.

**Comment by cjdd3b** [comment]
That sounds like it makes sense.

**Comment by rshorey** [comment]
closed by #60
