### ISSUE TITLE
Cycle-to-date totals: pull from cover sheet line items

### ISSUE THREAD

**Issue by cjdd3b** [newsdev/nyt-campfin#32]
Cycle-to-date summary information stored in the committees table should be pulled from cycle-to-date totals on cover sheets wherever possible. We should only calculate those fields as a last resort, and we should be sure to enumerate any that we do calculate.

**Comment by cjdd3b** [comment]
FYI: Ran a test on Hillary's filings from July and October and confirmed that the added-up totals don't match the numbers on the cover sheets.

**Comment by cjdd3b** [comment]
Confirmed that using cover sheets for this is, in fact, possible. Cycle-to-date totals are located in the F3PN line of standard .fec-formatted filings.

**Comment by rshorey** [comment]
dealt with for committees, no decision yet on whether we want to propagate these to candidates as well

**Comment by cjdd3b** [comment]
Unless @jeremyjbowers has objections, let's not duplicate those figures in candidates. In fact, let's rip those fields out of candidates entirely. Makes more sense to grab committee totals for a candidate dynamically for now, so we're not duplicating the same figures in two tables.
