### ISSUE TITLE
Figure out what to do with header files

### ISSUE THREAD

**Issue by cjdd3b** [newsdev/nyt-campfin#34]
Meanwhile, should this step be added to the bootstrapping docs?

cp -r $VIRTUAL_ENV/src/nyt-pyfec/pyfec/fec-csv-sources/ /tmp'

**Comment by rshorey** [comment]
this is resolved by 5c39efd3404bfb5aa5567b55757a34cec0abfc23 on nyt-pyfec, pip install it again and you should be good to go.
