### ISSUE TITLE
Use fecid as candidate primary key

### ISSUE THREAD

**Issue by cjdd3b** [newsdev/nyt-campfin#35]
Any reason we shouldn't do this? I like the idea of using FEC IDs for all FK references to keep the database more sane for Sarah.

**Comment by rshorey** [comment]
can we promise uniqueness? @jeremyjbowers seemed unsure that these aren't reused in different cycles.

**Comment by cjdd3b** [comment]
Good point. I'm not sure.

**Comment by rshorey** [comment]
In the old DB, it looks like we were storing a new version of each committee per cycle, in which case the FEC id can't be used as a unique key. Do we want committees to be persistent across cycles? If so, it looks like the fec_id can be used as a primary key.

**Comment by cjdd3b** [comment]
Ohhh, I see how this gets tricky. Summary totals. The old DB has a record for, say, the 2012 and 2016 versions of Committee X because the totals associated with them are cycle-specific. We should retain this behavior.

The real problem this was trying to solve is making sure the committees' FEC IDs are in the contributions and expenditures tables so they can more easily be queried by Sarah, etc. (rather than having to figure out how our internal IDs corresponded with FEC IDs). If we can just retain that info in those tables, it should be fine.

**Comment by rshorey** [comment]
Can we have a broader discussion about the post-2016 use of both the app and the data before I dig in here? I think there are some other design choices that would be better made earlier rather than later depending on how the data will be used when looking back to past cycles.

**Comment by cjdd3b** [comment]
Sure. Wanna chat later? I'm free around 4.

**Comment by rshorey** [comment]
yep!

**Comment by rshorey** [comment]
we decided we're not using fec_id as primary because it is unique in cycle but not outside of cycle, so we've got another pkey. But we basically ignore that ID for all purposes other than having a unique key, we use fec_id for everything. The django app has methods to access everything you need relying only on fec_id, and that's what should be done on the backend, too, taking cycle into account.
