### ISSUE TITLE
Decide whether to process refunds as contributions

### ISSUE THREAD

**Issue by cjdd3b** [newsdev/nyt-campfin#36]
Refunded contributions (SB28A's) are traditionally reported to the FEC as expenditures, but Derek's app includes them in the contributions table, which is important for calculating any totals based on itemizations.

We should get feedback from Sarah on this. But if we put them in expenditures, we'll need to be mindful to include them in any calculations (such as net primary) that take itemized contributions into account.

I stumbled onto this by running a test with Bernie's most recent filing (filing number 1029414) and comparing the results with Derek's app.

**Comment by cjdd3b** [comment]
Note: Turns out Derek's app includes these in both the expenditures and contributions tables.

**Comment by cjdd3b** [comment]
Derek's logic for this lives [here](https://github.com/newsdev/campaign_finance/blob/2016/lib/itemization_processor.rb#L43-L62).

**Comment by cjdd3b** [comment]
His logic also leaves a copy of these records in expenditures. I'm inclined to pick one table or the other.

**Comment by jsfenfen** [comment]
FWIW, my experience is that refunds are all over the place. Sometimes campaigns report them (incorrectly) as negative sked A items, sometimes they report them in the correct place. Sometimes they are in both places. This all gets cleaned up--I think--by FEC staff during 'exception handling' or something like that, and released in the bulk files, but it still remains a sore point when trying to make sense of the world from the raw filings.
