### ISSUE TITLE
Management command to delete all records associated with filing

### ISSUE THREAD

**Issue by cjdd3b** [newsdev/nyt-campfin#37]
In case something gets messed up. Should delete itemizations, delete the filing record, and ideally roll back summary totals to the previous filing, if any.

**Comment by rshorey** [comment]
@cjdd3b any intuition on what we should do with committee totals when we delete a filing?

Seems like the options are:
1) clear all committee totals
2) try to work backwards (subtract relevant totals)
3) try to find the most recent non-deleted filing and base the total on that

I think I like 3 best, but they're all somewhat risky. Thoughts?

**Comment by cjdd3b** [comment]
I think 3 is correct if it's feasible.
