### ISSUE TITLE
Make decisions about other itemization magic

### ISSUE THREAD

**Issue by cjdd3b** [newsdev/nyt-campfin#39]
Derek's itemization processor does a few other things that we should decide, with Sarah, whether to retain. The ones I've found are:

- [x] [Removing itemized lump sums of unitemized contributions](https://github.com/newsdev/campaign_finance/blob/2016/lib/itemization_processor.rb#L64-L83)

- [x] [Auto-flagging contributions and aggregates that exceed legal totals](https://github.com/newsdev/campaign_finance/blob/2016/lib/itemization_processor.rb#L168-L182)

- [x] [Auto-redesignating excess contributions](https://github.com/newsdev/campaign_finance/blob/2016/lib/itemization_processor.rb#L197-L211)

**Comment by rshorey** [comment]
there's a problem with the way pyfec is dealing with contributor_name which needs to be fixed before all of this can be done. https://github.com/newsdev/nyt-pyfec/issues/16

**Comment by rshorey** [comment]
- [ ] deactivate memo contribs

**Comment by cjdd3b** [comment]
Haha. I was just going to remind you of this after doing some testing.

**Comment by rshorey** [comment]
It became quickly apparent when I flagged 40k of Bernie's actblue
aggregates as over the limit :)
