### ISSUE TITLE
Field-by-field assessment of models.

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/nyt-campfin#4]
Make sure we're not missing fields we expect.

**Comment by rshorey** [comment]
do you mean:
1) check that the models capture everything the FEC is giving us?
or
2) check that everything the models are expecting is being populated?

**Comment by jeremyjbowers** [comment]
This would be a "work with Chase" issue to see that the fields we have are what he thinks we need to do the reporting.

**Comment by rshorey** [comment]
@cjdd3b do you have a moment to go over what you think is needed here?

**Comment by rshorey** [comment]
I think we're good on this one.
