### ISSUE TITLE
Tests!

### ISSUE THREAD

**Issue by rshorey** [newsdev/nyt-campfin#46]
- [x] create some fake fec CSVs
- [x] test imports
- [x] test deletions
- [x] test data transfer to committees
- [x] import newer filing from same committee
- [x] test amendments
- [x] test quarterly filings that supersede existing data
- [x] make sure import order does not matter
- [x] test amendment filed after subsequent quarterly filing
- [x] filing with 2 amendments, with both claiming to amend original filing
- [x] filing with 2 amendments, with amendment 2 claiming to amend amendment 1

**Comment by rshorey** [comment]
probably we need to make sure nothing bad happens if we try to load an amended filing and then the base filing in the wrong order. like probably throw an error and tell the user to start that committee from scratch, because that order would be a sign that something is really messed up with that committee,

**Comment by rshorey** [comment]
@cjdd3b, little thing, but if a filing is amended, should it be marked as active=false, in addition to amended_by? I think yes, but want to make sure I'm not missing something here.

**Comment by cjdd3b** [comment]
Yep! Records where active=True should be considered the full current set of
active filings and itemizations.
