### ISSUE TITLE
dates as strings

### ISSUE THREAD

**Issue by rshorey** [newsdev/nyt-campfin#58]
In a bunch of places (eg dissemination_date for a schedule E) we're storing dates as strings. Is there a good reason we're doing this @cjdd3b or @jeremyjbowers? If not, it would make finding/comparing much easier to store these all in the db as date fields.

**Comment by cjdd3b** [comment]
I like the idea of retaining the original string, just so we always have a
clear audit trail back to the original data (especially since dates are so
strict and gross in Postgres), but I definitely think we should add another
field that transforms it into an actual date.

**Comment by rshorey** [comment]
ok. I added some fields in places where we weren't retaining the original strings. I think we're good now in terms of both formatted and original.
