### ISSUE TITLE
load_commitee_filings should also include amendments

### ISSUE THREAD

**Issue by cjdd3b** [newsdev/nyt-campfin#59]
Running this command:

django-admin load_committee_filings --comm C00579458

Returns two filings for Jeb: filing IDs 1015075 (July) and 1029571 (October). But Jeb also filed an amendment to his July filing (ID: 1024106) that doesn't seem to have been picked up by the command.

Ideally it should be, and any calculated totals should reflect it. The reason is because there's an implication, at least to me, that running this command should effectively load in all filings necessary to get a current picture of a given committee. If an amendment supersedes a previous filing, it affects the current state of the committee and therefore should be included.

**Comment by rshorey** [comment]
#14 is listed as needing input from Sarah, so I've been ignoring amendments for now. Have we resolved whatever that issue was?

**Comment by cjdd3b** [comment]
Oh, cool! You've been ignoring them on purpose. That makes sense. I should
be able to map out a plan for amendment-handling today. Sarah and I have
talked about it quite a bit over the last couple months, so this solution
is a bit easier to map out than some of the other things we need her inoput
for.
