### ISSUE TITLE
Cover sheets for committees / filings.

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/nyt-campfin#6]
Should have totals available for filing deadline.

**Comment by rshorey** [comment]
Questions: totals by what? committee? it looks like those get pulled straight off the filing - is that what we want? do we want to aggregate to a higher level than filing?

**Comment by jeremyjbowers** [comment]
I think just the filing is good -- just needed to make sure those totals
were getting added to the model as part of the filings loader.


contact([{ "twitter": "@jeremybowers", "phone": "727-667-0510", "github": "
http://github.com/jeremyjbowers" }])

**Comment by rshorey** [comment]
These following are correctly being pulled from the filing:
coh_start
coh_end
new_loans
outstanding_loans
tot_raised
tot_contribs
tot_ite_contribs_indivs
tot_non_ite_contribs_indivs
tot_spent
tot_ies
tot_coordinated

Nothing is being populated for committees - for committee totals like cash on hand, total raised, etc, do we want to replace those with newer values?

**Comment by rshorey** [comment]
@jeremyjbowers, do we have any idea what this field on committee is: tot_coo_exp_par

there's no explanation. it's a decimal if that helps

**Comment by rshorey** [comment]
Committee totals are being added. Some committee fields are still a bit unclear to me, but I think the stuff specified in this issue is done.
