### ISSUE TITLE
total_unitemized_indiv and total_itemized_indiv reversed?

### ISSUE THREAD

**Issue by cjdd3b** [newsdev/nyt-campfin#61]
In the committees table, the total_unitemized_indiv and  total_itemized_indiv totals seem to be reversed. To replicate, load Jeb's filings:

django-admin load_committee_filings --comm C00579458

I'm seeing a total of 23010369.85 in unitemized and 1244622.73 in itemized. But looking at his [filing from October](http://docquery.fec.gov/cgi-bin/forms/C00579458/1029571/), those should be the other way around.

**Comment by cjdd3b** [comment]
This seems to be a problem in the filings table as well.

**Comment by rshorey** [comment]
hmm, I see it in the committee table (and the code that generates it) but not the filing table, can you double check? thx!

**Comment by cjdd3b** [comment]
It's named differently in filings. cycle_tot_ite_contribs_indivs (itemized)
and cycle_tot_non_ite_contribs_indivs (unitemized)

**Comment by rshorey** [comment]
Ah yes, I forgot to check cycle. Bowers specifically requested clear
differentiation between cycle and period for all aggregate fields - I will
make sure this is clear everywhere.
