### ISSUE TITLE
Committees: total_contributions is null?

### ISSUE THREAD

**Issue by cjdd3b** [newsdev/nyt-campfin#63]
If I load Jeb's filings:

django-admin load_committee_filings --comm C00579458

The total_contributions field in committees shows up as null. According to his [most recent filing](http://docquery.fec.gov/cgi-bin/forms/C00579458/1029571/), the total should be 24779029.78.

**Comment by rshorey** [comment]
this field is empty in almost all the CSV versions. total contributions should always be itemized+unitemized, right? If so, I will just do the math (and that's probably why it's empty, because it's totally calculable

**Comment by rshorey** [comment]
so it looks like we're not currently scraping contribs from party committees, other political committees or the candidate him/herself. I'm going to add these unless @cjdd3b says there's a good reason we're not. (Asked Bowers irl and he didn't have an opinion)

**Comment by cjdd3b** [comment]
Yeah, we should add these.
