### ISSUE TITLE
Committees: Command to delete filings from committee should zero out totals

### ISSUE THREAD

**Issue by cjdd3b** [newsdev/nyt-campfin#64]
If I run this:

django-admin delete_filings --comm C00579458

Jeb's totals still reflect the totals from the most recent filing. Ideally they'd be zeroed out to reflect the fact that none of his filings are in the system.

**Comment by cjdd3b** [comment]
Interestingly enough, if I just delete his most recent filing like this:

django-admin delete_filings --filing 1029571

The committee table totals recalculate properly (which is awesome)

**Comment by rshorey** [comment]
the totals get zero'd out and then we look for the most recent active filing and reset. If that's the desired behavior go ahead and close this issue, if we'd like something else let me know and I'll do it.

**Comment by cjdd3b** [comment]
Nope, that's correct. The issue is that when all filings are deleted (and there is no recent active filing), they totals don't seem to zero.

Also, FYI: As we look forward to amendments, it's worth double-checking how you define most recent. I outlined this a bit in #14, but it's possible that a committee files its October filing, then afterwards files an amended July filing. Technically that amendment would be more recent (in terms of when it was filed), but the October totals are the ones you'd want to keep. Not a problem now, but food for thought later.
