### ISSUE TITLE
SkedA: create and populate primary/general field

### ISSUE THREAD

**Issue by cjdd3b** [newsdev/nyt-campfin#65]
Derek called this pri_gen. It's just the first character of the election_code field. For example, if election_code is "P2016" this field would just be "P".

The main reason this is useful is so we can index it. It's used in a handful of calculations, and it will be handy in future cycles to not have to change the code to reflect the cycle ("2016") part of the string. Not urgent.

**Comment by rshorey** [comment]
1) should this also be on filing?
2) should it be on all transactions (skedB's and skedE's also seem to have this field)

**Comment by cjdd3b** [comment]
Yeah, that probably makes sense. It's most important for SkedA, but better
to be consistent.
