### ISSUE TITLE
Amendments are the worst

### ISSUE THREAD

**Issue by cjdd3b** [newsdev/nyt-campfin#78]
To replicate the error, try running this with a clean DB:

django-admin load_filings --start 2015-07-31 --end 2015-07-31

It's the mid-year filing deadline, and the folks at Right to Rise filed twice: once for their original report (filing id 1019371) and once to amend that report (filing id 1020117).

When the load_filings command is run, the amendment is loaded first. Then it attempts to load the original report, which results in this:

AssertionError: We don't have filing 1019371 but do have an amendment, that is very bad, you should probably delete and reload all filings for this committee

Seems they're being ingested out of order for some reason. Let me know if this is a painful fix and we might be able to work around.

**Comment by rshorey** [comment]
nope, refunds are worse. this fix shouldn't be too hard but will take a little thinking.

**Comment by rshorey** [comment]
I have a PR that addresses this, but it relies on a bit of a hack: whenever I scrape a list of amendments, it sorts by filing_id before importing anything. Assuming the FEC assigns filing_ids sequentially, which they always have, this will force the filings to be imported in the order they were filed. @cjdd3b given your greater knowledge of this process, do you foresee any issues with that method?

(both of the cases you cite above work if you start from a clean db)
