### ISSUE TITLE
Using range of dates seems to not trigger filing downloads

### ISSUE THREAD

**Issue by cjdd3b** [newsdev/nyt-campfin#91]
If I do this, the filings on 4/15 don't get picked up:

django-admin.py load_filings --start 2015-04-01 --end 2015-12-01

If I do this, they do:

django-admin.py load_filings --start 2015-04-15 --end 2015-04-15

**Comment by rshorey** [comment]
I can't replicate this - I ran exactly this command and got these filings. Are you sure you've loaded committees using the bootstrap command? Nothing without a committee will load unless you also specify  --all, but that will take forever for this long a range.

**Comment by cjdd3b** [comment]
I think I misinterpreted the order of operations after this command was run. Tried again and seems fine.
