### ISSUE TITLE
indexing

### ISSUE THREAD

**Issue by rshorey** [newsdev/nyt-campfin#95]
We're definitely going to need a bunch of indexes. I'm going to start with everything that acts like a foreign-key-like-thing on any model. @cjdd3b, any other tips?

**Comment by cjdd3b** [comment]
This was going to be my next feature branch, after I'm done with bulk loading. There are some fancy indexes I have to port over from the other app, so I figured I'd just do the whole thing. Cool?

**Comment by rshorey** [comment]
yep, definitely! I got started but will trash my branch.

**Comment by rshorey** [comment]
superseded by #100
